[package]
name = "expression"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.39"
pom = "3.4.0"
regex = "1.11.1"
thiserror = "2.0.11"

expression_derive = { path = "expression_derive", optional = true }

[features]
derive = ["expression_derive"]
default = ["derive"]
